---
- hosts: all
  gather_facts: no
  
  roles:
    - role: node-exporter-setup
      tags: [ never, node ]
    - role: cassandra-exporter-setup
      tags: [ never, cassandra ]
    - role: node-exporter-start
      tags: [ never, node_start ]
    - role: cassandra-exporter-start
      tags: [ never, cassandra_start ]
    - role: node-exporter-stop
      tags: [ never, node_stop ]
    - role: cassandra-exporter-stop
      tags: [ never, cassandra_stop ]
      
      #when:
      #  - '"cassandra" in ansible_run_tags'
      #  - '"start" in ansible_run_tags'