---
- hosts: cassandranodes
  gather_facts: yes
  
  roles:
    - role: spark-setup
      tags: [ never, setup ]
    - role: spark-job-deploy
      tags: [ never, job-deploy ]
    - role: spark-start
      tags: [ never, start ]
      when: inventory_hostname == spark_master
    - role: spark-stop
      tags: [ never, stop ]