{
 "title": "nodes-dashboard",
 "description": "Dashboard to view multiple servers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_uname_info{alias=\"$node\"}",
     "legendFormat": "{{sysname}} - {{release}} - {{version}}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node.+\"}*1000"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node.+\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node.+\", mode=\"system\"}) or count(node_cpu{instance=~\"$node.+\", mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"system\"}[5m])) * 100",
     "legendFormat": "system"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"user\"}[5m])) * 100",
     "legendFormat": "user"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"nice\"}[5m])) * 100",
     "legendFormat": "nice"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"steal\"}[5m])) * 100",
     "legendFormat": "steal"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"idle\"}[5m])) * 100",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"irq\"}[5m])) * 100",
     "legendFormat": "irq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"softirq\"}[5m])) * 100",
     "legendFormat": "softirq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~'$node.+',mode=\"guest\"}[5m])) * 100",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~'$node.+'} - node_memory_MemFree_bytes{instance=~'$node.+'} - node_memory_Buffers_bytes{instance=~'$node.+'} - node_memory_Cached_bytes{instance=~'$node.+'} - node_memory_SwapCached_bytes{instance=~'$node.+'} - node_memory_Slab_bytes{instance=~'$node.+'} - node_memory_PageTables_bytes{instance=~'$node.+'} - node_memory_VmallocUsed_bytes{instance=~'$node.+'} ) or ( node_memory_MemTotal{instance=~'$node.+'} - node_memory_MemFree{instance=~'$node.+'} - node_memory_Buffers{instance=~'$node.+'} - node_memory_Cached{instance=~'$node.+'} - node_memory_SwapCached{instance=~'$node.+'} - node_memory_Slab{instance=~'$node.+'} - node_memory_PageTables{instance=~'$node.+'} - node_memory_VmallocUsed{instance=~'$node.+'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$node.+'} or node_memory_Buffers{instance=~'$node.+'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node.+'} or node_memory_Cached{instance=~'$node.+'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node.+'} or node_memory_MemFree{instance=~'$node.+'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~'$node.+'} or node_memory_Slab{instance=~'$node.+'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$node.+'} or node_memory_SwapCached{instance=~'$node.+'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~'$node.+'} or node_memory_PageTables{instance=~'$node.+'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=~'$node.+'} or node_memory_VmallocUsed{instance=~'$node.+'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node.+'} - node_memory_SwapFree{instance=~'$node.+'}) or (node_memory_SwapTotal{instance=~'$node.+'} - node_memory_SwapFree{instance=~'$node.+'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~'$node.+'} or node_memory_Committed_AS{instance=~'$node.+'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~'$node.+'} or node_memory_Mapped{instance=~'$node.+'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~'$node.+'} or node_memory_Active{instance=~'$node.+'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=~'$node.+'} or node_memory_Inactive{instance=~'$node.+'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node.+\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{instance=~'$node.+',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{instance=~'$node.+',device !~'tmpfs',device!~'by-uuid'}) or 100.0 - 100 * (node_filesystem_avail{instance=~'$node.+',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{instance=~'$node.+',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node.+\"}[5m])*100 or irate(node_disk_io_time_ms{instance=~\"$node.+\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~'$node.+'}[5m]) or irate(node_disk_reads_completed{instance=~'$node.+'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~'$node.+'}[5m]) or irate(node_disk_writes_completed{instance=~'$node.+'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~'$node.+'}[5m]) or irate(node_disk_sectors_read{instance=~'$node.+'}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~'$node.+'}[5m]) or irate(node_disk_sectors_written{instance=~'$node.+'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_disk_io_now{instance=~\"$node.+\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$node.+\"}",
     "legendFormat": "open_fds_{{instance}}"
    },
    {
     "expr": "process_max_fds{instance=~\"$node.+\"}",
     "legendFormat": "max_fds_{{instance}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node.+\"}[5m]) or irate(node_context_switches{instance=~\"$node.+\"}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node.+'}[5m])*8 or irate(node_network_receive_bytes{instance=~'$node.+'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node.+'}[5m])*8 or irate(node_network_transmit_bytes{instance=~'$node.+'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node.+'}",
     "legendFormat": "established"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node.+\"}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node.+\"}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node.+\"}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node.+\"}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node.+\"} - node_nf_conntrack_entries{instance=~\"$node.+\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cassandra_stats{cluster=~\".+\",datacenter=~\".+\",instance=~\"$node.+\",job=~\".+\",name=\"java:lang:memory:heapmemoryusage:used\"} or jvm_memory_bytes_used{instance=~\"$node.+\", area=\"heap\"} or java_lang_memory_heapmemoryusage_used{instance=~\"$node.+\"}\r",
     "legendFormat": "HeapUsed_{{instance}}"
    },
    {
     "expr": "cassandra_stats{cluster=~\".+\",datacenter=~\".+\",instance=~\"$node.+\",job=~\".+\",name=\"java:lang:memory:heapmemoryusage:max\"} or jvm_memory_bytes_max{instance=~\"$node.+\", area=\"heap\"} or java_lang_memory_heapmemoryusage_max{instance=~\"$node.+\"}",
     "legendFormat": "HeapMax_{{instance}}"
    },
    {
     "expr": "cassandra_stats{cluster=~\".+\",datacenter=~\".+\",instance=~\"$node.+\",job=~\".+\",name=\"java:lang:memory:nonheapmemoryusage:used\"} or jvm_memory_bytes_used{instance=~\"$node.+\", area=\"nonheap\"} or java_lang_memory_nonheapmemoryusage_used{instance=~\"$node.+\"}",
     "legendFormat": "NonHeapUsed_{{instance}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{instance=~\"$node.+\",name=~\"java:lang:garbagecollector:.+:lastgcinfo:duration\"}, \"info\", \"$1\", \"name\", \"java:lang:garbagecollector:(.+?):lastgcinfo:duration\") or label_replace(jvm_gc_collection_seconds_sum{instance=~\"$node.+\"}/jvm_gc_collection_seconds_count{instance=~\"$node.+\"}, \"info\", \"$1\", \"gc\", \"PS (.+?)\") or label_replace(java_lang_garbagecollector_lastgcinfo_duration{instance=~\"$node.+\"}, \"info\", \"$1\", \"name\", \"java:lang:garbagecollector:(.+?):lastgcinfo:duration\")",
     "legendFormat": "{{info}}_{{instance}}"
    }
   ]
  }
 ]
}