{
 "title": "tomcat-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(tomcat_threadpool_acceptcount, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connection utilisation",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_connectioncount{instance='$node'}/tomcat_threadpool_maxconnections{instance='$node'}*100",
     "legendFormat": "ConnectionsUsed"
    }
   ]
  },
  {
   "title": "Thread utilisation",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{instance='$node'}/tomcat_threadpool_maxthreads{instance='$node'}*100",
     "legendFormat": "ThreadsUsed"
    }
   ]
  },
  {
   "title": "KeepAlive utilisation",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_keepalivecount{instance='$node'}/tomcat_threadpool_maxkeepaliverequests{instance='$node'}*100",
     "legendFormat": "KeepAliveUsed"
    }
   ]
  },
  {
   "title": "Tomcat Threadpool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptorthreadcount{instance=~'$node'}",
     "legendFormat": "{{instance}}_acceptorthreadcount"
    },
    {
     "expr": "tomcat_threadpool_connectioncount{instance=~'$node'}",
     "legendFormat": "{{instance}}_connectioncount"
    },
    {
     "expr": "tomcat_threadpool_currentthreadcount{instance=~'$node'}",
     "legendFormat": "{{instance}}_currentthreadcount"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{instance=~'$node'}",
     "legendFormat": "{{instance}}_currentthreadsbusy"
    },
    {
     "expr": "tomcat_threadpool_keepalivecount{instance=~'$node'}",
     "legendFormat": "{{instance}}_keepalivecount"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$node\", area=\"heap\"}",
     "legendFormat": "HeapUsed_{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"$node\", area=\"heap\"} ",
     "legendFormat": "HeapMax_{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_used{instance=\"$node\", area=\"nonheap\"} ",
     "legendFormat": "NonHeapUsed_{{instance}}"
    }
   ]
  },
  {
   "title": "Request rate by servlet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(tomcat_servlet_requestcount_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{servlet}}"
    }
   ]
  },
  {
   "title": "Error rate by servlet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(tomcat_servlet_errorcount_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{servlet}}"
    }
   ]
  },
  {
   "title": "Processing time rate by servlet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(tomcat_servlet_processingtime_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{servlet}}"
    }
   ]
  },
  {
   "title": "Sessions (rated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(tomcat_session_expiredsessions_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{context}}_expired"
    },
    {
     "expr": "irate(tomcat_session_processingtime_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{context}}_proctime"
    },
    {
     "expr": "irate(tomcat_session_rejectedsessions_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{context}}_rejected"
    },
    {
     "expr": "irate(tomcat_session_sessioncounter_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{context}}_session"
    }
   ]
  },
  {
   "title": "Byte rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(tomcat_bytesreceived_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{instance}}_received"
    },
    {
     "expr": "irate(tomcat_bytessent_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{instance}}_sent"
    }
   ]
  }
 ]
}