--- 
# THE CASSANDRA ROOTCA FILES MUST BE IN {{ cassandra_certificates_home }}
- name: check rootCA-cert exists
  stat:
    path: "{{ cassandra_certificates_home }}/ca-cert"
  register: cert

- fail:
    msg: "The ca-cert doesn't exist"
  when: cert.stat.exists == False
  
- name: check rootCA-key exists
  stat:
    path: "{{ cassandra_certificates_home }}/ca-key"
  register: key

- fail:
    msg: "The ca-key doesn't exist"
  when: key.stat.exists == False

- name: check server-truststore exists
  stat:
    path: "{{cassandra_certificates_home}}/server-truststore.jks"
  register: keyts
    
# Create truststore
- name: Create truststore
  shell: > 
    keytool -keystore {{cassandra_certificates_home}}/server-truststore.jks -alias CARoot -importcert 
    -file {{cassandra_certificates_home}}/ca-cert -keypass {{cassandra_ca_pw}} -storepass {{ cassandra_kt_pw }} -noprompt
  args: 
    executable: /bin/bash
  when: keyts.stat.exists == False
    
# For each node  
# Create keystore
- name: Create keystore
  shell: > 
    keytool -genkeypair -keyalg RSA -alias {{item}} -keystore {{cassandra_certificates_home}}/{{item}}.jks 
    -keypass {{ cassandra_kt_pw }} -storepass {{ cassandra_kt_pw }} -validity 730 -keysize 2048 
    -dname "CN={{item}}, OU=CassandraCluster, O=Organisation, C=COM"
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}"
  
# Creation request CSR
- name: Creation request CSR
  shell: > 
    keytool -keystore {{cassandra_certificates_home}}/{{item}}.jks -alias {{item}} -certreq 
    -file {{cassandra_certificates_home}}/{{item}}_cert_sr -keypass {{ cassandra_kt_pw }} -storepass {{ cassandra_kt_pw }}
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}"

# Signer certificat
- name: Signer certificat
  shell: > 
    openssl x509 -req -CA {{cassandra_certificates_home}}/ca-cert -CAkey {{cassandra_certificates_home}}/ca-key
    -in {{cassandra_certificates_home}}/{{item}}_cert_sr -out {{cassandra_certificates_home}}/{{item}}_cert_signed 
    -days 730 -CAcreateserial -passin pass:{{cassandra_ca_pw}}
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}"
  
# Attacher certificat rootCA au keystore
- name: Attach CA certificate au keystore
  shell: > 
    keytool -keystore {{cassandra_certificates_home}}/{{item}}.jks -alias CARoot -import -file {{cassandra_certificates_home}}/ca-cert 
    -noprompt -keypass {{ cassandra_kt_pw }} -storepass {{ cassandra_kt_pw }}
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}"
  
# Attacher certificat node au keystore
- name: Attacher certificat node au keystore
  shell: > 
    keytool -keystore {{cassandra_certificates_home}}/{{item}}.jks -alias {{item}} -import 
    -file {{cassandra_certificates_home}}/{{item}}_cert_signed -keypass {{ cassandra_kt_pw }} -storepass {{ cassandra_kt_pw }}
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}" 

# jks to p12
- name: jks to p12
  shell: > 
    keytool -importkeystore -srckeystore {{cassandra_certificates_home}}/{{item}}.jks -destkeystore {{cassandra_certificates_home}}/{{item}}.p12 
    -deststoretype PKCS12 -srcalias {{item}} -deststorepass {{ cassandra_kt_pw }} -destkeypass {{ cassandra_kt_pw }} 
    -srcstorepass {{ cassandra_kt_pw }} -srckeypass {{ cassandra_kt_pw }}
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}"
  
# Extract certificate pem from p12
- name: Extract certificate pem from p12
  shell: > 
    openssl pkcs12 -in {{cassandra_certificates_home}}/{{item}}.p12 -nokeys -out {{cassandra_certificates_home}}/{{item}}.cer.pem -passin pass:{{ cassandra_kt_pw }}
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}"
  
# Extract key pem from p12
- name: Extract key pem from p12
  shell: > 
    openssl pkcs12 -in {{cassandra_certificates_home}}/{{item}}.p12 -nodes -nocerts -out {{cassandra_certificates_home}}/{{item}}.key.pem -passin pass:{{ cassandra_kt_pw }}
  args: 
    executable: /bin/bash    
  loop: "{{ cassandra_certificates_hosts }}"

# chmod key
- name: chmod key
  file:
    path: "{{cassandra_certificates_home}}/{{item}}.key.pem"
    mode: '0400'
  loop: "{{ cassandra_certificates_hosts }}"

# Create folder for certificates    
- name: Creates directory for certificates
  file: path="{{cassandra_certificates_home}}/{{env_domain}}" state=directory
  
# mv jks and pem
- name: mv jks and pem
  shell: > 
    mv -f {{cassandra_certificates_home}}/{{item}}.*.pem {{cassandra_certificates_home}}/{{item}}.jks {{cassandra_certificates_home}}/{{env_domain}}/
  args: 
    executable: /bin/bash
  loop: "{{ cassandra_certificates_hosts }}"
  
# Find temporary files
- name: Find temporary files
  find:
    paths: "{{cassandra_certificates_home}}"
    patterns: "*_cert_signed,*_cert_sr,*.srl,*.p12"
  register: wildcard_files_to_delete

# Remove temporary files
- name: Remove temporary files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ wildcard_files_to_delete.files }}"
  
  # chmod trustore
- name: chmod trustore
  file:
    path: "{{cassandra_certificates_home}}/server-truststore.jks"
    mode: '0644'
