---
# Remove temporary files for safety
- name: Remove temporary files
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "{{ cassandra_data_dir }}/filestobackup"
    - "{{ cassandra_data_dir }}/tokens"
    - "{{ cassandra_data_dir }}/full_schema.cql"
      
# Run nodetool cleanup to ensure that invalid replicas are removed
- name: nodetool cleanup
  command: ./nodetool -u {{ cassandra_user }} -pw {{ cassandra_pw[env_domain] }} cleanup
  args:
    chdir: "{{ cassandra_home }}/current_cassandra/bin/"

# Save the token ranges
- name: nodetool ring
  shell: ./nodetool -u {{ cassandra_user }} -pw {{ cassandra_pw[env_domain] }} ring | grep {{ ansible_default_ipv4.address }} | awk '{print $NF ","}' > {{ cassandra_data_dir }}/tokens
  args:  
    executable: /bin/bash 
    chdir: "{{ cassandra_home }}/current_cassandra/bin/"

# Format tokens so they are directly usable by initial_token
- name: Format tokens so they are directly usable by initial_token
  shell: sed -i -e ':a;N;$! ba;s/\n//g' -e 's/.$//g' {{ cassandra_data_dir }}/tokens
  args:  
    executable: /bin/bash
    warn: False
         
# Describe keyspaces schema 
- name: desc keyspaces schema 
  shell: ./cqlsh {{inventory_hostname}} {{cassandra_ssl}} -u {{ cassandra_user }} -p {{ cassandra_pw[env_domain] }} -e 'desc schema' > {{ cassandra_data_dir }}/full_schema.cql   
  args:
    executable: /bin/bash
    chdir: "{{ cassandra_home }}/current_cassandra/bin/"

# Clear the snapshot for safety
- name: nodetool clearsnapshot
  command: ./nodetool -u {{ cassandra_user }} -pw {{ cassandra_pw[env_domain] }} clearsnapshot -t archive
  args:
    chdir: "{{ cassandra_home }}/current_cassandra/bin/"
  
# Create the snapshot hardlinks for the SSTables
- name: nodetool snapshot
  command: ./nodetool -u {{ cassandra_user }} -pw {{ cassandra_pw[env_domain] }} snapshot -t archive
  args:
    chdir: "{{ cassandra_home }}/current_cassandra/bin/"

# Backup commands
# Incremental: dsmc incremental -su=yes <path>
# Full / archive: dsmc archive -su=yes -desc=<date> -archmc=<retention_policy> <path>

# Choose correct retention and backup command
- name: Set the correct retention policy depending on day of week and day of month
  set_fact:
    retention_policy: "{{retention_policy_month}}"
  when: ansible_date_time.weekday == snapshot_day[env_domain] and ansible_date_time.day|int <= 7

- name: Set the correct retention policy depending on day of week and day of month and month
  set_fact:
    retention_policy: "{{retention_policy_year}}"
  when: ansible_date_time.weekday == snapshot_day[env_domain] and ansible_date_time.day|int <= 7 and ansible_date_time.month|int == 12

- name: Set the correct backup command depending on day of week and day of month
  set_fact:
    command_backup: "{{ command_archive }} -archmc={{ retention_policy }}"
  when: ansible_date_time.weekday == snapshot_day[env_domain] and ansible_date_time.hour == snapshot_time[env_domain]
  
# Find the snapshot directories
- name: Find the snapshot directories
  shell: find {{ cassandra_data_dir }}/ -exec sh -c 'printf "%s\n" "$0"' {} \; | grep archive | xargs -n 1 echo $@ >> {{ cassandra_data_dir }}/filestobackup 
  args:
    executable: /bin/bash

# Add schema
- name: Add schema to filestobackup
  lineinfile:
    path: "{{ cassandra_data_dir }}/filestobackup"
    line: "{{ cassandra_data_dir }}/full_schema.cql"
    insertbefore: BOF

# Add tokens
- name: Add tokens to filestobackup
  lineinfile:
    path: "{{ cassandra_data_dir }}/filestobackup"
    line: "{{ cassandra_data_dir }}/tokens"
    insertbefore: BOF
    
# Add nodes
- name: Add nodes to filestobackup
  lineinfile:
    path: "{{ cassandra_data_dir }}/filestobackup"
    line: "{{ cassandra_data_dir }}/nodes"
    insertbefore: BOF
  when: cassandra_extra_opts == "-e"

# Upload to TSM
- name: Upload to TSM
  shell: "timeout {{ timeout }} {{ command_backup }} -filelist={{ cassandra_data_dir }}/filestobackup" 
  args:
    executable: /bin/bash
  register: dsmc_out
  failed_when: dsmc_out.rc != 0

# Show backup outs
- name: Show backup results
  debug:
    var: dsmc_out

# Verify they are in TSM?  
#- name: Find the snapshot directories
#  command:  dsmc q ba {{ cassandra_data_dir }} 
#  args:
#    executable: /bin/bash
#  register: dsmc_ver_out
  
# Clear the snapshot
- name: nodetool clearsnapshot
  command: ./nodetool -u {{ cassandra_user }} -pw {{ cassandra_pw[env_domain] }} clearsnapshot -t archive
  args:
    chdir: "{{ cassandra_home }}/current_cassandra/bin/"

# Remove temporary files
- name: Remove temporary files
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "{{ cassandra_data_dir }}/filestobackup"
    - "{{ cassandra_data_dir }}/tokens"
    - "{{ cassandra_data_dir }}/full_schema.cql"
