--- 
# Create folder for the templates
- name: Create folder for the templates
  file:
    path: "{{ blackbox_home }}/openshift/blackbox/"
    state: directory
    mode: 0755

# Templates
- name: Templates
  template:
    src: "{{item.src}}"
    dest: "{{ blackbox_home }}/openshift/blackbox/{{item.dst}}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644
  with_items:
    - { src: templates/blackbox.yml.j2, dst: blackbox.yml }
    - { src: templates/template.yml.j2, dst: template.yml }
    - { src: templates/statefulset.yml.j2, dst: statefulset.yml }
    - { src: templates/service.yml.j2, dst: service.yml }
    - { src: templates/serviceaccount.yml.j2, dst: serviceaccount.yml }
    - { src: templates/route.yml.j2, dst: route.yml }

# Create yml from small partial ymls
- name: Create yml from small partial ymls 
  shell: >
    cat template.yml blackbox.yml serviceaccount.yml statefulset.yml service.yml route.yml > blackbox_deploy.yml
  args:
    executable: /bin/bash
    chdir: "{{ blackbox_home }}/openshift/blackbox/"
    
# Create components in OpenShift
- name: Create yml from small partial ymls 
  shell: "{{blackbox_home}}/bin/oc process -f blackbox_deploy.yml -o yaml | {{blackbox_home}}/bin/oc create -f-"
  args:
    executable: /bin/bash
    chdir: "{{ blackbox_home }}/openshift/blackbox/"
  register: out_oc
  
# Show create outs
- name: Show create results
  debug: 
    var: out_oc