--- 
# THE CASSANDRA ROOTCA FILES MUST BE IN {{ cassandra_certificates_home }}
# Copy certificate files
- name: Create CA directory if it does not exist
  file:
    path: /home/{{ansible_ssh_user}}/CA
    state: directory

- name: Copy certificate files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: "{{ cassandra_certificates_home }}/{{env_domain}}/{{inventory_hostname}}.jks",     dest: "{{ cassandra_home }}/current_cassandra/conf/{{inventory_hostname}}.jks" }
    - { src: "{{ cassandra_certificates_home }}/{{env_domain}}/{{inventory_hostname}}.cer.pem", dest: "/home/{{ansible_ssh_user}}/CA/{{inventory_hostname}}.cer.pem" }
    - { src: "{{ cassandra_certificates_home }}/{{env_domain}}/{{inventory_hostname}}.key.pem", dest: "/home/{{ansible_ssh_user}}/CA/{{inventory_hostname}}.key.pem" }
    - { src: "{{ cassandra_certificates_home }}/server-truststore.jks", dest: "{{ cassandra_home }}/current_cassandra/conf/server-truststore.jks" }
  